Repository devopsloft/devopsloft, pull requests merged in 2019-06, with the labels that each got.

#265 added statistics tab + checks by selenium
  Vagrantfile
  app_s2i/application.py
  app_s2i/templates/includes/_navbar.html
  app_s2i/templates/statistics.html
  scripts/bootstrap.sh
  spin.cmd
  tests/navbar.py
  tests/requirements-test.txt
Labels: topic: python, topic: selenium, topic: travis

#264 improve documentation
  README.md
  app_s2i/templates/home.html
Labels: documentation

#271 Spin to python
  requirements.txt
  spin.py
Labels: topic: python

#272 adding defaults
  requirements.txt
  spin.py
Labels: topic: python

#273 Feature/spin to python
  createPemFiles.py
  requirements.txt
  spin.py
Labels: topic: python

#269 vault persistent storage
  .env
Labels: topic: vagrant

#274 Feature/spin to python
  requirements.txt
  spin.py
Labels: topic: python, topic: vagrant

#277 vault ci
  .travis.yml
  requirements.txt
  scripts/bootstrap.sh
  tests/requirements-test.txt
  tests/test_vault.py
  tests/vault.py
  vault/config.hcl.j2
Labels: topic: bash, topic: jinja2, topic: python, topic: selenium, topic: travis
