Repository devopsloft/devopsloft, pull requests merged in 2019-05, with the labels that each got.

#217 frontend - jumbotron
  web_s2i/static/css/style.css
  web_s2i/templates/home.html
  web_s2i/templates/includes/_jumbotron.html
  web_s2i/templates/includes/_navbar.html
  web_s2i/templates/layout.html
Labels: enhancement

#218 favicon
  web_s2i/static/favicon/favicon-16x16.png
  web_s2i/static/favicon/favicon-32x32.png
  web_s2i/static/favicon/favicon.ico
  web_s2i/templates/includes/_favicon.html
  web_s2i/templates/layout.html
Labels: enhancement

#219 vault upgrade pip
  vault_s2i/Dockerfile
Labels: enhancement

#221 pin slack python version
  web_s2i/Dockerfile
  web_s2i/requirements.txt
Labels: bug

#222 Shorter build time
  vault_s2i/Dockerfile
Labels: enhancement

#223 fixing regdering errors
  web_s2i/templates/layout.html
Labels: bug

#224 Improved jumbotron styling
  web_s2i/static/css/style.css
  web_s2i/templates/layout.html
Labels: enhancement

#225 ignore all pem files
  .gitignore
Labels: enhancement

#226 travis docker-compose
  .env
  .travis.yml
  Vagrantfile
  docker-compose.yml
  tests/is_table_empty.py
  web_s2i/application.py
Labels: enhancement

#227 continue if trigger failed
  Vagrantfile
Labels: enhancement

#228 wrapper script
  spin.sh
Labels: enhancement

#229 vagrant-docker-compose plugin
  Vagrantfile
Labels: enhancement

#230 rename web service
  Vagrantfile
  app_s2i/Dockerfile
  app_s2i/application.py
  app_s2i/events.py
  app_s2i/requirements.txt
  app_s2i/static/css/style.css
  app_s2i/static/favicon/favicon-16x16.png
  app_s2i/static/favicon/favicon-32x32.png
  app_s2i/static/favicon/favicon.ico
  app_s2i/static/logo.png
  app_s2i/templates/contact.html
  app_s2i/templates/docslist.html
  app_s2i/templates/home.html
  app_s2i/templates/includes/_favicon.html
  app_s2i/templates/includes/_footer.html
  app_s2i/templates/includes/_formhelpers.html
  app_s2i/templates/includes/_jumbotron.html
  app_s2i/templates/includes/_messages.html
  app_s2i/templates/includes/_navbar.html
  app_s2i/templates/layout.html
  app_s2i/templates/login.html
  app_s2i/templates/resources.html
  app_s2i/templates/signup.html
  app_s2i/templates/utils/loader.html
  docker-compose.yml
  scripts/set-environment-variables.sh
Labels: enhancement

#231 nginx
  .env
  Vagrantfile
  docker-compose.yml
  web_s2i/Dockerfile
  web_s2i/nginx.conf
Labels: enhancement

#232 set ENVIRONMENT
  .travis.yml
  Vagrantfile
  docker-compose.yml
  scripts/set-environment-variables.sh
Labels: enhancement

#233 fix nginx errors
  web_s2i/nginx.conf
Labels: bug

#234 remove copying env file
  .travis.yml
  Vagrantfile
  docker-compose.yml
  scripts/set-environment-variables.sh
Labels: enhancement

#235 share service - initial commit
  Vagrantfile
  app_s2i/events.py
  devopsloft.yml
  docker-compose.yml
  modules/loft_hvac.py
  share_s2i/Dockerfile
  share_s2i/events.py
  share_s2i/requirements.txt
Labels: enhancement

#236 beautify Vagrantfile
  Vagrantfile
Labels: enhancement

#237 meetup auth
  Vagrantfile
  app_s2i/application.py
  app_s2i/requirements.txt
  docker-compose.yml
  share_s2i/events.py
Labels: enhancement

#238 stage elastic ip
  .env
  Vagrantfile
Labels: enhancement

#239 share service
  .travis.yml
  app_s2i/application.py
  app_s2i/events.py
  app_s2i/requirements.txt
  app_s2i/templates/share.html
  docker-compose.yml
  modules/loft_meetup.py
  share_s2i/Dockerfile
  share_s2i/requirements.txt
Labels: enhancement

#241 added windows version of spin script
  spin.cmd
Labels: enhancement

#242 yet another step towards the share page
  .travis.yml
  Vagrantfile
  docker-compose.yml
  modules/loft_hvac.py
  modules/loft_meetup.py
  python_modules/is_member_exists.py
  scripts/docker-compose-provision.sh
  scripts/vault-init.sh
  tests/basic_http_get_test.py
  vault_cli_s2i/Dockerfile
  vault_cli_s2i/application.py
  vault_s2i/Dockerfile
  vault_s2i/vault-init.py
Labels: enhancement

#243 initalize secrets and enable the share function
  .env
  .gitignore
  Vagrantfile
  app_s2i/Dockerfile
  app_s2i/application.py
  app_s2i/events.py
  app_s2i/requirements.txt
  docker-compose.yml
  modules/loft_hvac.py
  modules/loft_meetup.py
  record-set.json.j2
  requirements.txt
  scripts/bootstrap.sh
  scripts/docker-compose-provision.sh
  scripts/dump-db.sh
  scripts/load-db.sh
  scripts/vault-init.py
  scripts/vault-init.sh
  spin.sh
  vault_cli_s2i/Dockerfile
  vault_cli_s2i/application.py
  vault_s2i/vault-init.py
Labels: enhancement

#195 [Fix #119] ssl certificates
  .env
  .travis.yml
  Vagrantfile
  app_s2i/Dockerfile
  docker-compose.yml
  scripts/bootstrap.sh
  scripts/docker-compose-provision.sh
  scripts/dump-db.sh
  scripts/load-db.sh
  spin.sh
  tests/basic_http_get_test.py
  web_s2i/Dockerfile
  web_s2i/nginx.conf
Labels: enhancement

#246 [Fixes #245] multiple AWS profiles
  .env
  Vagrantfile
  spin.sh
Labels: enhancement

#248 [Fix #247] ports 80+443 in stage and prod
  .env
  .travis.yml
  Vagrantfile
  app_s2i/Dockerfile
  docker-compose.yml
  scripts/docker-compose-provision.sh
  spin.sh
  web_s2i/Dockerfile
  web_s2i/nginx.conf.j2
  web_s2i/requirements.txt
Labels: topic: AWS, topic: bash, topic: docker, topic: docker-compose, topic: jinja2, topic: nginx, topic: travis, topic: vagrant

#251 private ip
  Vagrantfile
Labels: topic: vagrant

#252 Prune vagrant boxes
  spin.sh
Labels: topic: bash, topic: vagrant

#254 [Fix #253] Use selenium tests in travis ci
  .travis.yml
  tests/navbar.py
  tests/requirements-test.txt
Labels: topic: python, topic: selenium, topic: travis
